-- =====================================================
-- Migration 010: Complete sparks for days 51-200
--
-- Adds 150 more daily sparks so Today has content
-- every day of the year (not just days 1-50).
--
-- 6-category rotation: connect → mindful → move →
-- create → learn → joy → connect ...
-- =====================================================

insert into public.daily_sparks (day_of_year, title, prompt, emoji, color, points, proof_type) values
  (51, 'Voice memo friend', 'Send a 60-sec voice note to a friend instead of texting.', '🎙️', '#E6ABE1', 10, 'screenshot'),
  (52, 'Three deep breaths', 'Stop. Three slow deep breaths. Name how you feel in one word.', '🫁', '#F8D5F3', 10, 'text'),
  (53, 'Walking call', 'Take one call today while walking. No sitting allowed.', '📞', '#E6ABE1', 10, 'text'),
  (54, 'Doodle 5 minutes', 'Doodle anything for 5 minutes. Photo the result.', '✏️', '#E6ABE1', 10, 'screenshot'),
  (55, 'Read 15 mins', 'Read anything that''s not work for 15 mins. Share what.', '📚', '#E8B044', 10, 'text'),
  (56, 'Wear something bright', 'Wear something colorful today. Photo or just confirm.', '🌈', '#F8D5F3', 10, 'text'),
  (57, 'Compliment a stranger', 'Give a real compliment to someone you don''t know today.', '😊', '#E8B044', 10, 'screenshot'),
  (58, '5-4-3-2-1 grounding', 'Name 5 things you see, 4 hear, 3 feel, 2 smell, 1 taste.', '🧘', '#E6ABE1', 10, 'text'),
  (59, 'Stretch the body', 'Stand and stretch every joint for 90 seconds.', '🤸', '#E8B044', 10, 'text'),
  (60, 'Write a haiku', '5-7-5 syllables. About anything. Share it.', '🌸', '#F8D5F3', 10, 'screenshot'),
  (61, 'TED talk short', 'Find a TED talk under 12 mins. Watch it. One sentence learned.', '🎬', '#F8D5F3', 10, 'text'),
  (62, 'Dessert first', 'Eat dessert as your first meal today (small one). For science.', '🍰', '#E6ABE1', 10, 'text'),
  (63, 'Old colleague check-in', 'Message a former coworker out of the blue. Just to say hi.', '👋', '#F8D5F3', 10, 'screenshot'),
  (64, 'Drink water slowly', 'Pour a glass of water. Drink it without doing anything else.', '💧', '#E8B044', 10, 'text'),
  (65, '15-min walk', 'Walk outside for 15 minutes. Phone in pocket. Photo or note.', '🚶', '#5C8C5A', 10, 'text'),
  (66, 'Photo of something blue', 'Find one interesting blue thing today. Photo.', '💙', '#E8B044', 10, 'screenshot'),
  (67, 'New word', 'Find one word you don''t know. Use it in a sentence.', '📖', '#E6ABE1', 10, 'text'),
  (68, 'Skip somewhere', 'Skip (the way kids do) for 30 seconds where nobody can see.', '🤸', '#E8B044', 10, 'text'),
  (69, 'Ask the deeper question', 'Ask someone ''how are you really?'' Listen to the answer.', '💭', '#E6ABE1', 10, 'screenshot'),
  (70, 'Cloud-watching', 'Look up at the sky for 60 full seconds. Just look.', '☁️', '#F8D5F3', 10, 'text'),
  (71, 'Take the stairs', 'Skip the elevator today, every time.', '🪜', '#F8D5F3', 10, 'text'),
  (72, 'Build paper plane', 'Make a paper plane and throw it. Photo of the flight.', '✈️', '#E6ABE1', 10, 'screenshot'),
  (73, 'Podcast on unknown', 'Pick a 20-min podcast on a topic you know nothing about.', '🎧', '#925F3A', 10, 'text'),
  (74, 'Car karaoke', 'Sing in the car or shower. Loud. The whole song.', '🎤', '#F8D5F3', 10, 'text'),
  (75, 'Coffee for someone', 'Bring or buy a coffee for someone unexpected.', '☕', '#925F3A', 10, 'screenshot'),
  (76, 'Hold the warmth', 'Hold a warm drink with both hands. Notice the warmth.', '☕', '#925F3A', 10, 'text'),
  (77, 'Dance to one song', 'Play one song. Dance the whole way through. Alone or not.', '💃', '#E6ABE1', 10, 'text'),
  (78, 'Arrange found things', 'Arrange small objects into a tiny sculpture. Photo.', '🪴', '#925F3A', 10, 'screenshot'),
  (79, 'Wikipedia rabbit hole', 'Open a random Wikipedia article. Follow links for 10 mins.', '🔍', '#E8B044', 10, 'text'),
  (80, 'Mismatched socks', 'Wear mismatched socks today. Tell us about it.', '🧦', '#E6ABE1', 10, 'text'),
  (81, 'Mom call', 'Call a parent or guardian. Five minutes minimum.', '📞', '#E6ABE1', 10, 'screenshot'),
  (82, 'Notice one bite', 'Eat one bite of a meal slowly. Notice texture, flavor, temperature.', '🍴', '#E6ABE1', 10, 'text'),
  (83, '50 jumping jacks', 'Right now. 50 jumping jacks. Confirm done.', '🤸‍♀️', '#E8B044', 10, 'text'),
  (84, 'Sketch your hand', 'Draw your non-dominant hand with your dominant one. 5 min.', '✋', '#E8B044', 10, 'screenshot'),
  (85, 'Watch documentary', 'Watch 30 mins of any documentary. What surprised you?', '📺', '#F8D5F3', 10, 'text'),
  (86, 'Slow ice cream', 'Eat ice cream. Slowly. Don''t rush. No phone.', '🍦', '#E8B044', 10, 'text'),
  (87, 'Recommend something', 'Recommend a book/show/podcast to someone specific.', '📖', '#E8B044', 10, 'screenshot'),
  (88, 'Smell something', 'Smell something on purpose — flower, soap, coffee. Just smell.', '👃', '#E8B044', 10, 'text'),
  (89, 'Sun salutation', 'One round of sun salutation. Or 5 mins of any movement.', '🧘‍♀️', '#F8D5F3', 10, 'text'),
  (90, '6-word memoir', 'Write your life story in exactly 6 words.', '📝', '#F8D5F3', 10, 'screenshot'),
  (91, 'Etymology hunt', 'Pick a word. Look up its origin. Tell us.', '🔤', '#E6ABE1', 10, 'text'),
  (92, 'Whistle a tune', 'Whistle (or hum) a song. Anywhere. Loud enough to hear.', '🎶', '#F8D5F3', 10, 'text'),
  (93, 'Lunch with someone new', 'Eat lunch with someone you don''t usually talk to.', '🍱', '#F8D5F3', 10, 'screenshot'),
  (94, 'Touch grass', 'Stand on grass with bare feet for 30 seconds.', '🌱', '#5C8C5A', 10, 'text'),
  (95, 'Posture hour', 'Sit up straight for one full hour. Set a timer.', '💺', '#925F3A', 10, 'text'),
  (96, 'Pin a quote', 'Find a quote that matches your mood. Save it somewhere visible.', '💬', '#E6ABE1', 10, 'screenshot'),
  (97, 'Read a poem', 'Find one poem online. Read it slowly. Share the line that hit.', '📜', '#925F3A', 10, 'text'),
  (98, 'Mirror silly faces', 'Make silly faces in a mirror. 60 seconds.', '😵', '#925F3A', 10, 'text'),
  (99, 'Forgive silently', 'Forgive someone for a small thing without telling them.', '🕊️', '#E6ABE1', 10, 'screenshot'),
  (100, 'Watch the sunset', 'Watch the sunset or look out a west-facing window at dusk.', '🌇', '#F8D5F3', 10, 'text'),
  (101, 'Quick run', 'Run for 60 seconds. Doesn''t matter where, just go.', '🏃', '#5C8C5A', 10, 'text'),
  (102, 'Tiny origami', 'Fold something out of any paper. Doesn''t have to be good.', '🦢', '#5C8C5A', 10, 'screenshot'),
  (103, 'Listen to old music', 'Listen to music from before you were born for 15 min.', '🎵', '#E8B044', 10, 'text'),
  (104, 'Dance party of one', 'Put on one song. Dance the whole way through, alone, in private.', '💃', '#E6ABE1', 10, 'text'),
  (105, 'Share a song', 'Send a song to someone with a one-line why.', '🎵', '#E8B044', 10, 'screenshot'),
  (106, 'Single-task lunch', 'Eat one meal with no screen, no book, no phone. Just eat.', '🍽️', '#E6ABE1', 10, 'text'),
  (107, 'Neck rolls', '10 slow neck rolls each direction. Notice tension.', '👤', '#E6ABE1', 10, 'text'),
  (108, 'Photo shadows', 'Find an interesting shadow. Photo it.', '🕯️', '#925F3A', 10, 'screenshot'),
  (109, 'Map study', 'Study a map of a country you''ve never been to. Note 3 things.', '🗺️', '#F8D5F3', 10, 'text'),
  (110, 'Fancy mug', 'Use your fanciest mug today. Even for water.', '🍵', '#E8B044', 10, 'text'),
  (111, 'Tell the truth gently', 'Tell someone something kind you''ve been thinking but not saying.', '💌', '#F8D5F3', 10, 'screenshot'),
  (112, 'Body scan', 'From toes to crown, notice one body part at a time. 2 minutes.', '🧠', '#E8B044', 10, 'text'),
  (113, 'Wall push-ups', '10 wall push-ups. Right now. Anywhere.', '💪', '#E8B044', 10, 'text'),
  (114, 'Thank-you note', 'Write a thank-you note to someone. Doesn''t have to mail it.', '💌', '#E6ABE1', 10, 'screenshot'),
  (115, 'Tutorial of your choice', 'Watch a 10-min tutorial on something you''ve wanted to learn.', '📹', '#E6ABE1', 10, 'text'),
  (116, 'Indoor sunglasses', 'Wear sunglasses indoors for one meeting/call.', '😎', '#F8D5F3', 10, 'text'),
  (117, 'Old photo send', 'Find an old photo and send it to whoever''s in it.', '📷', '#E6ABE1', 10, 'screenshot'),
  (118, 'Gratitude triple', 'Write 3 things you''re grateful for. Specific, not generic.', '📝', '#F8D5F3', 10, 'text'),
  (119, 'Standing meeting', 'Take one meeting standing today.', '🧍', '#F8D5F3', 10, 'text'),
  (120, '1-line poem', 'Write one sentence that could be a poem. Share it.', '📜', '#F8D5F3', 10, 'screenshot'),
  (121, 'Read a recipe', 'Read a recipe for something you''d never normally cook.', '🍜', '#925F3A', 10, 'text'),
  (122, 'Talk to a plant', 'Talk to a plant or houseplant. Out loud. 30 seconds.', '🪴', '#5C8C5A', 10, 'text'),
  (123, 'Cross-team hello', 'Say hi to someone on a different team for no reason.', '🤝', '#E8B044', 10, 'screenshot'),
  (124, 'No-phone hour', 'One hour with your phone in another room. Notice the urge.', '📵', '#925F3A', 10, 'text'),
  (125, 'Hydrate quick', 'Drink two full glasses of water back to back. Now.', '💧', '#E6ABE1', 10, 'text'),
  (126, 'Logo for your day', 'Sketch a logo for how today feels. 30 seconds, no perfection.', '🎨', '#E8B044', 10, 'screenshot'),
  (127, 'Read about a hero', 'Read about someone you admire for 15 mins. Share one quote.', '👑', '#E8B044', 10, 'text'),
  (128, 'High-five yourself', 'Give yourself a high-five (clap loudly) for something you did.', '✋', '#E6ABE1', 10, 'text'),
  (129, 'Thank a teacher', 'Reach out to a teacher who shaped you. Even briefly.', '👩‍🏫', '#925F3A', 10, 'screenshot'),
  (130, 'Light a candle', 'Light a candle. Watch it for 60 seconds before doing anything.', '🕯️', '#E6ABE1', 10, 'text'),
  (131, 'Walk backwards', 'Walk backwards for 30 seconds (where safe). Notice the strangeness.', '🔙', '#925F3A', 10, 'text'),
  (132, 'Cooking remix', 'Try a recipe and change one ingredient. See what happens.', '🍳', '#E6ABE1', 10, 'screenshot'),
  (133, 'Trivia in a topic', 'Find 3 surprising facts about an everyday object you use.', '💡', '#F8D5F3', 10, 'text'),
  (134, 'Wrong hand writing', 'Write your name with your non-dominant hand. Photo it.', '✍️', '#925F3A', 10, 'text'),
  (135, 'Listen, don''t fix', 'Listen to someone today without offering advice or solutions.', '👂', '#F8D5F3', 10, 'screenshot'),
  (136, 'Notice what''s draining', 'Write down one thing draining your energy. Just notice it.', '🌫️', '#925F3A', 10, 'text'),
  (137, 'Cat-cow stretch', '5 cat-cow stretches on hands and knees. Slow.', '🐈', '#E8B044', 10, 'text'),
  (138, 'Photo reflections', 'Find a reflection (puddle, window, mirror). Photo it.', '🪞', '#F8D5F3', 10, 'screenshot'),
  (139, 'Learn one phrase', 'Learn one phrase in a language you don''t speak.', '🗣️', '#E6ABE1', 10, 'text'),
  (140, 'Find what makes you laugh', 'Find one thing that makes you laugh out loud today.', '😂', '#E8B044', 10, 'text'),
  (141, 'Hand-written note', 'Write a real paper note to someone. Mail or hand-deliver.', '✉️', '#E6ABE1', 10, 'screenshot'),
  (142, 'Step into morning slow', 'Take 50% longer on your morning routine. Notice what changes.', '🌅', '#E8B044', 10, 'text'),
  (143, 'Touch your toes', 'Bend forward. See where you can reach. No judgement.', '🦶', '#F8D5F3', 10, 'text'),
  (144, 'Color one page', 'Color one page in a coloring book. Or print one.', '🖍️', '#E6ABE1', 10, 'screenshot'),
  (145, 'Read old letter', 'Find any old letter (email/text/paper). Read it slowly.', '✉️', '#925F3A', 10, 'text'),
  (146, 'Sing in the shower', 'Sing in the shower. Full song. No phone.', '🚿', '#F8D5F3', 10, 'text'),
  (147, 'Birthday early', 'Wish someone happy birthday early. They''ll remember.', '🎂', '#E8B044', 10, 'screenshot'),
  (148, 'Listen to silence', 'Sit in silence for 5 minutes. Don''t fix anything.', '🤫', '#F8D5F3', 10, 'text'),
  (149, 'Shoulder rolls', '10 shoulder rolls forward, 10 back. Feel where it''s tight.', '🤷', '#E6ABE1', 10, 'text'),
  (150, 'Stack of coins', 'Stack coins into a tiny tower. Photo before it falls.', '🪙', '#925F3A', 10, 'screenshot'),
  (151, 'Watch a how-to', 'Watch any ''how-to'' that doesn''t apply to you. Why''s it cool?', '🔧', '#E8B044', 10, 'text'),
  (152, 'Weird voices', 'Read something aloud in a weird voice. To yourself counts.', '🎭', '#E6ABE1', 10, 'text'),
  (153, 'Tell a kid a story', 'Tell a child (yours or someone else''s) a real story.', '🧒', '#F8D5F3', 10, 'screenshot'),
  (154, 'Notice your hands', 'Look at your hands for a moment. Really look. They''ve done a lot.', '✋', '#E6ABE1', 10, 'text'),
  (155, 'Take a brisk walk', 'Walk briskly for 10 minutes. Don''t stop until the timer ends.', '🚶‍♀️', '#5C8C5A', 10, 'text'),
  (156, 'Make tea from scratch', 'Make tea with loose leaves or fresh ingredients. Slow.', '🍵', '#5C8C5A', 10, 'screenshot'),
  (157, 'Country deep-dive', 'Pick a country. Read its Wikipedia intro. Share 1 fact.', '🌍', '#F8D5F3', 10, 'text'),
  (158, 'Pirate talk', 'Talk like a pirate for an hour. Voice memo proof if you dare.', '🏴‍☠️', '#925F3A', 10, 'text'),
  (159, 'Send flowers', 'Send flowers or something fresh to someone unexpected.', '🌸', '#E6ABE1', 10, 'screenshot'),
  (160, 'Pet an animal', 'If you can, pet a dog/cat/animal mindfully for 2 minutes.', '🐈', '#E8B044', 10, 'text'),
  (161, 'Plank 30 sec', 'Plank for 30 seconds. Even a wonky one counts.', '💪', '#E8B044', 10, 'text'),
  (162, 'Sticky-note art', 'Draw something tiny on a sticky note. Leave it somewhere kind.', '🟨', '#E8B044', 10, 'screenshot'),
  (163, 'Listen to a debate', 'Listen to 15 mins of a debate on something you don''t care about.', '🎙️', '#E6ABE1', 10, 'text'),
  (164, 'Make a TikTok dance', 'Learn one TikTok dance move. Even badly. Video optional.', '📱', '#E8B044', 10, 'text'),
  (165, 'Reconnect briefly', 'Send a one-sentence ''thinking of you'' to someone.', '💌', '#E8B044', 10, 'screenshot'),
  (166, 'Box breathing', '4 in, 4 hold, 4 out, 4 hold. Repeat 8 times.', '🫁', '#F8D5F3', 10, 'text'),
  (167, 'March in place', 'March in place for 2 minutes. Knees up.', '🦵', '#F8D5F3', 10, 'text'),
  (168, 'Photo your breakfast', 'Style your breakfast like a magazine photo. Then eat it.', '🥐', '#F8D5F3', 10, 'screenshot'),
  (169, 'Read an essay', 'Find one essay online. Read it fully. Share one quote.', '📝', '#925F3A', 10, 'text'),
  (170, 'Wear a costume piece', 'Wear one costume-y item today (hat/scarf/glasses). Photo.', '🎩', '#F8D5F3', 10, 'text'),
  (171, 'Compliment creator', 'Compliment an online creator on something specific they made.', '⭐', '#F8D5F3', 10, 'screenshot'),
  (172, 'Phone-free meal', 'Eat a meal with phone in another room. Tell us what came up.', '🍽️', '#E6ABE1', 10, 'text'),
  (173, 'Lunge across room', 'Walking lunges from one side of a room to the other.', '🏋️', '#E6ABE1', 10, 'text'),
  (174, 'Paragraph of morning', 'Write one paragraph about your morning. Casual. Send it.', '✍️', '#E6ABE1', 10, 'screenshot'),
  (175, 'Watch sport explained', 'Watch a ''how does X sport work'' video. Pick anything obscure.', '🏆', '#E8B044', 10, 'text'),
  (176, 'Random act of kindness', 'Do something kind for a stranger today. Anonymously.', '💝', '#E6ABE1', 10, 'text'),
  (177, 'Group meal plan', 'Invite friends to a meal — even just coffee.', '🍽️', '#E6ABE1', 10, 'screenshot'),
  (178, 'Sky-color check', 'What color is the sky right now? Step outside and notice.', '🌈', '#E8B044', 10, 'text'),
  (179, 'Stretch hamstrings', 'Reach for your toes. Sit and reach. Don''t bounce.', '🦵', '#925F3A', 10, 'text'),
  (180, 'Make a playlist', 'Build a 30-min playlist for someone specific. Tell us the vibe.', '🎵', '#E8B044', 10, 'screenshot'),
  (181, 'Read about your city', 'Read 5 mins about your city''s history. Share something new.', '🏙️', '#F8D5F3', 10, 'text'),
  (182, 'Walk a new route', 'Take a different route home. Or to the kitchen. Just different.', '🚶', '#5C8C5A', 10, 'text'),
  (183, 'Listen to elder', 'Ask an older person about their younger years. Note one thing.', '👵', '#925F3A', 10, 'screenshot'),
  (184, 'Sit and don''t fix', 'Sit somewhere for 5 minutes without trying to improve anything.', '🪑', '#925F3A', 10, 'text'),
  (185, 'Child''s pose', '5 minutes in child''s pose. Listen to your body.', '🧘', '#E8B044', 10, 'text'),
  (186, 'Photograph 3 colors', 'Find 3 objects matching a single color. Photo them.', '🎨', '#F8D5F3', 10, 'screenshot'),
  (187, 'Animal documentary', 'Watch 15 mins of an animal documentary. Wonder a bit.', '🦒', '#5C8C5A', 10, 'text'),
  (188, 'Crayon doodle', 'Doodle with crayons or markers for 5 minutes. Color outside.', '🖍️', '#E8B044', 10, 'text'),
  (189, 'Tell a teammate', 'Tell a teammate one specific thing they do well.', '🙌', '#E8B044', 10, 'screenshot'),
  (190, 'Hands-warm-soap', 'Wash your hands slowly, noticing temperature and soap. 30 seconds.', '🧼', '#F8D5F3', 10, 'text'),
  (191, 'Triceps stretch', 'Stretch each tricep for 30 seconds. Feels great after typing.', '💪', '#F8D5F3', 10, 'text'),
  (192, 'Story from object', 'Pick a random object. Write a 3-sentence story about it.', '📖', '#925F3A', 10, 'screenshot'),
  (193, 'Listen to a lecture', 'Find a university lecture online. Watch 20 mins.', '🎓', '#E6ABE1', 10, 'text'),
  (194, 'Drink fancy', 'Make any drink (coffee/tea/water) extra fancy today.', '🍸', '#F8D5F3', 10, 'text'),
  (195, 'Voice note family', 'Voice-note a family member you haven''t spoken to in 2+ weeks.', '💌', '#F8D5F3', 10, 'screenshot'),
  (196, 'Right-now check', 'Pause. Where are you? What''s around you? What''s true right now?', '📍', '#E6ABE1', 10, 'text'),
  (197, 'Whole-body shake', 'Stand and shake your whole body for 30 seconds. Loosen up.', '💃', '#E6ABE1', 10, 'text'),
  (198, 'Window collage', 'Photograph 4 windows that interest you. Make a 4-up grid.', '🪟', '#E6ABE1', 10, 'screenshot'),
  (199, 'Read a manual', 'Open a manual for something you own. Read 5 mins. Find one thing.', '📋', '#925F3A', 10, 'text'),
  (200, 'Laugh at yourself', 'Find one thing about yourself that''s silly. Laugh at it kindly.', '🤣', '#E6ABE1', 10, 'text')
on conflict (day_of_year) do nothing;
